# Generated by Django 2.2.3 on 2019-07-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=50)),
                ('alamat_lengkap', models.TextField(max_length=500)),
                ('masakan', models.CharField(max_length=30)),
                ('rerata_harga', models.IntegerField()),
                ('kontak', models.CharField(max_length=20)),
                ('buka_jam', models.TimeField()),
                ('tutup_jam', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('nilai', models.FloatField()),
                ('rm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloning.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pict_url', models.URLField()),
                ('rm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloning.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(max_length=500)),
                ('harga', models.PositiveIntegerField()),
                ('rm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloning.Restaurant')),
            ],
        ),
    ]
