# Generated by Django 2.2.3 on 2019-07-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rerata_harga',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='the_choices',
            field=models.ManyToManyField(to='cloning.Kategori'),
        ),
    ]
